import type { MeasureType } from "./schema";

export type SeedIngredient = {
  name: string;
  measureType: MeasureType;
  /** Grams per millilitre. Approximate, for converting spoons and cups. */
  gramsPerMl?: number;
  countUnit?: string;
  gramsEach?: number;
};

const weight = (name: string, gramsPerMl: number): SeedIngredient => ({
  name,
  measureType: "weight",
  gramsPerMl,
});
const volume = (name: string, gramsPerMl: number): SeedIngredient => ({
  name,
  measureType: "volume",
  gramsPerMl,
});
const count = (name: string, countUnit: string, gramsEach?: number, gramsPerMl?: number): SeedIngredient => ({
  name,
  measureType: "count",
  countUnit,
  gramsEach,
  gramsPerMl,
});

/**
 * Starter library of common UK ingredients. Densities are typical values for the form
 * the ingredient is usually measured in (ground spices, chopped vegetables, and so on).
 * Oils are classed as weight (a tbsp of olive oil is 13.8 g); other liquids as volume.
 */
export const seedIngredients: SeedIngredient[] = [
  // Oils and fats
  weight("Olive oil", 0.92),
  weight("Extra virgin olive oil", 0.92),
  weight("Vegetable oil", 0.92),
  weight("Rapeseed oil", 0.92),
  weight("Sunflower oil", 0.92),
  weight("Sesame oil", 0.92),
  weight("Coconut oil", 0.92),
  weight("Butter", 0.96),
  weight("Ghee", 0.9),

  // Dairy and liquids
  volume("Whole milk", 1.03),
  volume("Semi-skimmed milk", 1.03),
  volume("Double cream", 1.0),
  volume("Single cream", 1.01),
  volume("Buttermilk", 1.03),
  weight("Natural yoghurt", 1.03),
  weight("Greek yoghurt", 1.05),
  weight("Crème fraîche", 1.0),
  weight("Cream cheese", 1.0),
  weight("Cheddar", 0.45),
  weight("Parmesan", 0.4),
  weight("Mozzarella", 1.0),
  weight("Feta", 1.0),
  weight("Halloumi", 1.05),
  weight("Paneer", 1.05),
  count("Egg", "egg", 58),

  // Stocks, sauces and condiments
  volume("Water", 1.0),
  volume("Chicken stock", 1.0),
  volume("Vegetable stock", 1.0),
  volume("Beef stock", 1.0),
  count("Stock cube", "cube", 10),
  volume("Soy sauce", 1.2),
  volume("Dark soy sauce", 1.2),
  volume("Fish sauce", 1.2),
  volume("Worcestershire sauce", 1.1),
  volume("White wine vinegar", 1.01),
  volume("Cider vinegar", 1.01),
  volume("Rice vinegar", 1.01),
  volume("Balsamic vinegar", 1.1),
  volume("Lemon juice", 1.03),
  volume("Lime juice", 1.03),
  volume("Mirin", 1.15),
  volume("White wine", 0.99),
  volume("Red wine", 0.99),
  volume("Vanilla extract", 0.88),
  weight("Honey", 1.42),
  weight("Maple syrup", 1.32),
  weight("Golden syrup", 1.43),
  weight("Tomato ketchup", 1.14),
  weight("Tomato purée", 1.1),
  weight("Passata", 1.03),
  weight("Dijon mustard", 1.05),
  weight("Wholegrain mustard", 1.05),
  weight("Mayonnaise", 0.95),
  weight("Harissa", 1.1),
  weight("Curry paste", 1.1),
  weight("Miso paste", 1.15),
  weight("Gochujang", 1.2),
  weight("Sriracha", 1.1),
  weight("Sweet chilli sauce", 1.2),
  weight("Hoisin sauce", 1.25),
  weight("Oyster sauce", 1.2),
  weight("Peanut butter", 1.1),
  weight("Tahini", 1.05),

  // Tins
  count("Tinned chopped tomatoes", "tin", 400),
  count("Tinned coconut milk", "tin", 400),
  count("Tinned kidney beans", "tin", 400),
  count("Tinned chickpeas", "tin", 400),
  count("Tinned black beans", "tin", 400),
  count("Tinned cannellini beans", "tin", 400),
  count("Tinned butter beans", "tin", 400),
  count("Tinned sweetcorn", "tin", 325),
  count("Tinned tuna", "tin", 145),

  // Baking and dry goods
  weight("Plain flour", 0.53),
  weight("Self-raising flour", 0.53),
  weight("Strong bread flour", 0.55),
  weight("Wholemeal flour", 0.55),
  weight("Cornflour", 0.51),
  weight("Caster sugar", 0.85),
  weight("Granulated sugar", 0.85),
  weight("Soft brown sugar", 0.8),
  weight("Icing sugar", 0.5),
  weight("Table salt", 1.2),
  weight("Sea salt flakes", 0.55),
  weight("Black pepper", 0.45),
  weight("Baking powder", 0.9),
  weight("Bicarbonate of soda", 0.95),
  weight("Dried yeast", 0.65),
  weight("Cocoa powder", 0.5),
  weight("Dark chocolate", 0.65),
  weight("Rolled oats", 0.4),
  weight("Breadcrumbs", 0.45),
  weight("Desiccated coconut", 0.35),

  // Spices, dried
  weight("Ground cumin", 0.45),
  weight("Ground coriander", 0.4),
  weight("Ground turmeric", 0.55),
  weight("Paprika", 0.5),
  weight("Smoked paprika", 0.5),
  weight("Chilli powder", 0.5),
  weight("Chilli flakes", 0.35),
  weight("Cayenne pepper", 0.5),
  weight("Garam masala", 0.45),
  weight("Curry powder", 0.45),
  weight("Ground cinnamon", 0.55),
  weight("Ground ginger", 0.45),
  weight("Ground nutmeg", 0.5),
  weight("Mustard powder", 0.5),
  weight("Cumin seeds", 0.55),
  weight("Coriander seeds", 0.4),
  weight("Mustard seeds", 0.7),
  weight("Fennel seeds", 0.45),
  weight("Cardamom pods", 0.35),
  count("Star anise", "star", 1),
  count("Bay leaf", "leaf", 0.2),
  count("Cinnamon stick", "stick", 3),
  weight("Dried oregano", 0.2),
  weight("Dried thyme", 0.3),
  weight("Dried mixed herbs", 0.25),

  // Fresh herbs and aromatics
  weight("Fresh coriander", 0.1),
  weight("Fresh parsley", 0.1),
  weight("Fresh basil", 0.1),
  weight("Fresh mint", 0.1),
  weight("Fresh rosemary", 0.15),
  weight("Fresh thyme", 0.15),
  count("Garlic", "clove", 5, 0.6),
  weight("Fresh ginger", 0.65),
  count("Red chilli", "chilli", 15),
  count("Green chilli", "chilli", 15),
  count("Lemon", "lemon", 100),
  count("Lime", "lime", 65),
  weight("Lemongrass", 0.5),

  // Rice, grains, pulses, pasta
  weight("Basmati rice", 0.85),
  weight("Long grain rice", 0.85),
  weight("Jasmine rice", 0.85),
  weight("Brown rice", 0.8),
  weight("Arborio rice", 0.85),
  weight("Couscous", 0.7),
  weight("Bulgur wheat", 0.7),
  weight("Quinoa", 0.75),
  weight("Pearl barley", 0.8),
  weight("Red lentils", 0.85),
  weight("Green lentils", 0.8),
  weight("Dried pasta", 0.45),
  weight("Spaghetti", 0.45),
  weight("Egg noodles", 0.4),
  weight("Rice noodles", 0.4),
  count("Tortilla wrap", "wrap", 40),
  count("Naan", "naan", 130),

  // Nuts, seeds, dried fruit
  weight("Whole almonds", 0.6),
  weight("Flaked almonds", 0.35),
  weight("Cashews", 0.6),
  weight("Peanuts", 0.6),
  weight("Walnuts", 0.45),
  weight("Pine nuts", 0.55),
  weight("Sesame seeds", 0.6),
  weight("Sunflower seeds", 0.55),
  weight("Pumpkin seeds", 0.55),
  weight("Chia seeds", 0.7),
  weight("Raisins", 0.65),
  weight("Sultanas", 0.65),
  weight("Dried apricots", 0.55),

  // Meat, fish, protein
  weight("Chicken breast", 1.0),
  weight("Chicken thigh", 1.0),
  weight("Minced beef", 1.0),
  weight("Minced lamb", 1.0),
  weight("Minced pork", 1.0),
  weight("Minced turkey", 1.0),
  weight("Beef braising steak", 1.0),
  weight("Pork shoulder", 1.0),
  weight("Lamb shoulder", 1.0),
  weight("Bacon", 1.0),
  weight("Chorizo", 1.0),
  weight("Salmon fillet", 1.0),
  weight("Cod fillet", 1.0),
  weight("Prawns", 1.0),
  weight("Tofu", 1.05),

  // Vegetables and fruit
  weight("Onion", 0.65),
  weight("Red onion", 0.65),
  weight("Shallot", 0.65),
  weight("Spring onions", 0.4),
  weight("Leek", 0.4),
  weight("Carrot", 0.55),
  weight("Celery", 0.5),
  weight("Potato", 0.7),
  weight("Sweet potato", 0.7),
  weight("Butternut squash", 0.6),
  weight("Courgette", 0.55),
  weight("Aubergine", 0.4),
  weight("Red pepper", 0.6),
  weight("Green pepper", 0.6),
  weight("Tomato", 0.75),
  weight("Cherry tomatoes", 0.65),
  weight("Spinach", 0.15),
  weight("Frozen spinach", 0.65),
  weight("Kale", 0.15),
  weight("Cabbage", 0.4),
  weight("Broccoli", 0.4),
  weight("Cauliflower", 0.45),
  weight("Green beans", 0.45),
  weight("Frozen peas", 0.65),
  weight("Frozen sweetcorn", 0.65),
  weight("Mushrooms", 0.35),
  weight("Cucumber", 0.55),
  weight("Lettuce", 0.2),
  weight("Beetroot", 0.65),
  weight("Parsnip", 0.55),
  weight("Swede", 0.65),
  count("Avocado", "avocado", 150),
];
